#!/bin/bash
set -e

SEND_ENV=(HOST USER_ROOT AUTHORIZED_KEYS_ROOT USER_COUNT)

for ((i=1; i <= USER_COUNT; i++ )); do
  SEND_ENV+=(USER_$i AUTHORIZED_KEYS_$i WEECHAT_PASSWORD_$i WEECHAT_PORT_$i)
done

requireEnv "${SEND_ENV[@]}"

function runScript
{
  set_env=()
  send_env=()
  set_env_reverse=()

  for var in "${SEND_ENV[@]}"; do
    lc_var="LC_$var"
    set_env+=("$lc_var=${!var}")
    set_env_reverse+=("$var=\"\$$lc_var\"")
    send_env+=("$lc_var")
  done

  run="chmod +x setup/bin/$1 && $(IFS=' '; echo "${set_env_reverse[*]}") setup/bin/$1"
  send_env_list=$(IFS=','; echo "${send_env[*]}")
  env "${set_env[@]}" ssh -o SendEnv="$send_env_list" "$USER_ROOT@$HOST" "$run"
}
